const container = document.querySelector("#container");
const content = document.createElement("div");
content.classList.add("content");
content.textContent = "this is the glorious text-content!";
container.appendChild(content);
const paragraph = document.createElement("p");
paragraph.classList.add("paragraph");
paragraph.textContent = "Hey im red!!";
paragraph.style.cssText = "color:red";
container.appendChild(paragraph);
const input = document.createElement("h3");
input.classList.add("inputs");
input.textContent = "i'm a blue h3 !! woooooooow";
input.style.cssText = "color:blue";
container.appendChild(input);
const block = document.createElement("div");
block.classList.add("diva");
block.style.backgroundColor = "pink";
block.style.border = "1px solid black";
const title = document.createElement("h1");
title.classList.add("title");
title.textContent = "i'm in div ?";
block.appendChild(title);
const minnieParagraph = document.createElement("p");
minnieParagraph.classList.add("para");
minnieParagraph.textContent = "ME TOOOOOO YAAAAAAAYY ";
block.appendChild(minnieParagraph);
container.appendChild(block);
